### PR TITLE
Compatibility with official active_scaffold gem

### PR DESCRIPTION
**Pull request by courtland**
It would be nice if this gem also worked with the official active_scaffold fork, since there are no changes necessary other than removing the gems runtime dependency on active_scaffold_vho.

### CODE REVIEW

**Comment by courtland** [comment]
I've also fixed batch update and create to work under rails 3.1.x.

**Comment by vhochstein** [comment]
Thanks a lot, but I prefer to have a seperate activescaffold ecosystem.

**Comment by vhochstein** [comment]
Will close it.

**Comment by courtland** [comment]
OK I figured. Thanks anyways.

There is still a bug under rails 3.1 that I fixed that you may want to pull
into your tree.

On Thu, Jan 12, 2012 at 1:31 PM, Volker Hochstein <
reply@reply.github.com

**Pull request closed without merging**
